services:
  queuearr:
    image: queuearr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queuearr
    restart: unless-stopped
    ports:
      - "3000:${QUEUEARR_PORT:-80}"
    volumes:
      - ${DATA_PATH}:/app/data
    environment:
      - PORT=${QUEUEARR_PORT:-80}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - PLEX_CLIENT_ID=${PLEX_CLIENT_ID}
      - PLEX_SERVER_MACHINE_IDENTIFIER=${PLEX_SERVER_MACHINE_IDENTIFIER}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - TRANSMISSION_URL=${TRANSMISSION_URL}
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT:-mailto:admin@queuearr.local}
      - QUEUEARR_DATA_DIR=/app/data

volumes:
  queuearr-data:
